In [ ]:
import numpy as np

def gaussian_elimination(matrix):
    """
    Performs Gaussian elimination on an augmented matrix to bring it to
    Row Echelon Form (REF).

    Args:
        matrix (np.ndarray): The augmented matrix (M x N).

    Returns:
        np.ndarray: The matrix in Row Echelon Form.
    """

    # 1. Initialization
    # Work on a copy of the matrix, and ensure it's a float type
    # to handle non-integer values during elimination.
    A = matrix.astype(float).copy()
    num_rows, num_cols = A.shape

    pivot_row = 0
    pivot_col = 0

    # 2. Main Loop
    # We iterate through the matrix, defining a pivot (pivot_row, pivot_col)
    # at each step.
    while pivot_row < num_rows and pivot_col < num_cols:

        # 3. Partial Pivoting
        # Find the row with the largest absolute value in the current pivot column
        # (at or below the current pivot row) and swap it with the current pivot row.
        # This improves numerical stability and avoids division by zero.

        # Find index of max value in the current column, starting from pivot_row
        max_row_idx = np.argmax(np.abs(A[pivot_row:, pivot_col])) + pivot_row

        # Swap the current pivot row with the max_row
        if max_row_idx != pivot_row:
            A[[pivot_row, max_row_idx]] = A[[max_row_idx, pivot_row]]

        # 4. Handle Zero Pivot
        # Get the pivot element
        pivot_element = A[pivot_row, pivot_col]

        # If the pivot element is (close to) zero, this column is linearly
        # dependent. We can't use it as a pivot.
        # So, we skip to the next column (but stay on the same row).
        if np.isclose(pivot_element, 0):
            pivot_col += 1
            continue # Go to the next iteration of the while loop

        # 5. Elimination
        # Create zeros in all rows below the current pivot row in the pivot column.
        for i in range(pivot_row + 1, num_rows):
            # Get the factor needed to eliminate the element at (i, pivot_col)
            factor = A[i, pivot_col] / pivot_element

            # Perform the row operation: R_i = R_i - factor * R_pivot
            # We apply this to the entire row (or at least from the pivot column on).
            A[i, pivot_col:] = A[i, pivot_col:] - factor * A[pivot_row, pivot_col:]

        # 6. Move to Next Pivot
        # We are done with the current pivot row and column, so we move
        # down and to the right.
        pivot_row += 1
        pivot_col += 1

    return A

if __name__ == "__main__":
    # Set print options for numpy for cleaner output
    np.set_printoptions(precision=4, suppress=True)

    # --- Example 1: Standard 3x3 system ---
    # 2x +  y -  z =  8
    # -3x -  y + 2z = -11
    # -2x +  y + 2z = -3
    A1 = np.array([
        [2,  1, -1,  8],
        [-3, -1,  2, -11],
        [-2,  1,  2, -3]
    ], dtype=float)

    print("--- Example 1 ---")
    print("Original Matrix:\n", A1)
    ref1 = gaussian_elimination(A1)
    print("\nRow Echelon Form:\n", ref1)
    print("-" * 20)

    # --- Example 2: Needs Pivoting ---
    # 0x + 2y + 3z = 4
    # 1x + 1y - 1z = 0
    # 2x + 4y - 5z = 2
    A2 = np.array([
        [0, 2, 3, 4],
        [1, 1, -1, 0],
        [2, 4, -5, 2]
    ], dtype=float)

    print("--- Example 2 (Needs Pivoting) ---")
    print("Original Matrix:\n", A2)
    ref2 = gaussian_elimination(A2)
    print("\nRow Echelon Form:\n", ref2)
    print("-" * 20)

    # --- Example 3: A dependent system (will result in a zero row) ---
    # 1x + 2y + 3z = 4
    # 2x + 4y + 6z = 8
    # 1x + 1y + 1z = 1
    A3 = np.array([
        [1, 2, 3, 4],
        [2, 4, 6, 8],
        [1, 1, 1, 1]
    ], dtype=float)

    print("--- Example 3 (Dependent System) ---")
    print("Original Matrix:\n", A3)
    ref3 = gaussian_elimination(A3)
    print("\nRow Echelon Form:\n", ref3)
    print("-" * 20)

--- Example 1 ---
Original Matrix:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Row Echelon Form:
 [[ -3.      -1.       2.     -11.    ]
 [  0.       1.6667   0.6667   4.3333]
 [  0.       0.       0.2     -0.2   ]]
--------------------
--- Example 2 (Needs Pivoting) ---
Original Matrix:
 [[ 0.  2.  3.  4.]
 [ 1.  1. -1.  0.]
 [ 2.  4. -5.  2.]]

Row Echelon Form:
 [[ 2.  4. -5.  2.]
 [ 0.  2.  3.  4.]
 [ 0.  0.  3.  1.]]
--------------------
--- Example 3 (Dependent System) ---
Original Matrix:
 [[1. 2. 3. 4.]
 [2. 4. 6. 8.]
 [1. 1. 1. 1.]]

Row Echelon Form:
 [[ 2.  4.  6.  8.]
 [ 0. -1. -2. -3.]
 [ 0.  0.  0.  0.]]
--------------------
