In [1]:
import numpy as np

def gaussian_elimination(A, b):
    """
    Solves Ax = b using Gaussian elimination with partial pivoting.
    """
    A = A.astype(float).copy() # Operate on a copy to avoid modifying original
    b = b.astype(float).copy()
    n = len(b)

    # Forward Elimination
    for i in range(n):
        # Find the row with the largest absolute value in column i
        max_row = i + np.argmax(np.abs(A[i:, i]))

        # Swap rows in A and b
        A[[i, max_row]] = A[[max_row, i]]
        b[[i, max_row]] = b[[max_row, i]]

        # Eliminate entries below pivot
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        sum_ax = np.dot(A[i, i+1:], x[i+1:])
        x[i] = (b[i] - sum_ax) / A[i, i]

    return x

In [2]:
A = np.array([[2, 3],
              [5, 4]])

b = np.array([8, 13])

solution = gaussian_elimination(A, b)
print(solution)

[1. 2.]


In [13]:
def cholesky_decomposition(A):
    """
    Performs Cholesky decomposition: A = L * L.T
    Assumes A is symmetric and positive definite.
    """
    n = A.shape[0]
    L = np.zeros((n, n))

    for i in range(n):
        for j in range(i+1):
            s = np.dot(L[i, :j], L[j, :j])

            if i == j:
                # Diagonal elements
                d = A[i, i] - s

                if d <= 0:
                    raise ValueError(f"Matrix is not Positive Definite. Error at diagonal index {i}. Val: {d}")

                L[i, j] = np.sqrt(d)
            else:
                # Off-diagonal elements
                L[i, j] = (A[i, j] - s) / L[j, j]

    return L

In [5]:
A = np.array([[4, 2],
              [2, 3]])

L = cholesky_decomposition(A)
print(L)

[[2.         0.        ]
 [1.         1.41421356]]


In [12]:
# Input: 3 Row Vectors that are "dense" (no zeros) and correlated.
# These vectors point in similar directions, forcing the algorithm to
# subtract large projections to find the orthogonal components.

vectors = [
    [3.0, 2.0, 1.0],  # Vector v1
    [2.0, 3.0, 1.0],  # Vector v2
    [1.0, 1.0, 3.0]   # Vector v3
]

# Run the function
basis = gram_schmidt(vectors)

print("Original Vectors:\n", np.array(vectors))
print("-" * 20)
print("Orthogonal Basis (Result):\n", basis)
print("-" * 20)

# Verification: The dot product of different rows should be ~0 (Orthogonal)
# Let's check dot product of row 0 and row 1
dot_0_1 = np.dot(basis[0], basis[1])
dot_0_2 = np.dot(basis[0], basis[2])
dot_1_2 = np.dot(basis[1], basis[2])

print(f"Verification (Dot products should be 0):")
print(f"Row 0 . Row 1: {dot_0_1:.5f}")
print(f"Row 0 . Row 2: {dot_0_2:.5f}")
print(f"Row 1 . Row 2: {dot_1_2:.5f}")

Original Vectors:
 [[3. 2. 1.]
 [2. 3. 1.]
 [1. 1. 3.]]
--------------------
Orthogonal Basis (Result):
 [[ 3.          2.          1.        ]
 [-0.78571429  1.14285714  0.07142857]
 [-0.48148148 -0.48148148  2.40740741]]
--------------------
Verification (Dot products should be 0):
Row 0 . Row 1: 0.00000
Row 0 . Row 2: 0.00000
Row 1 . Row 2: 0.00000


In [14]:
vectors = [
    [3, 1],
    [2, 2]
]

orthogonal_vectors = gram_schmidt(vectors)
print(orthogonal_vectors)

[[ 3.   1. ]
 [-0.4  1.2]]
